name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acrcomunidadecloud.azurecr.io/mycontainer:$(date +%s)
      
    - name: Push the docker image
      run: docker push acrcomunidadecloud.azurecr.io/myconmtainer:$(date +%s)
    

