name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
     
      - uses: azure/docker-login@v1
        with:
          login-server: yourACRname.azurecr.io
          username: ${{ secrets.DOCKERACR_USERNAME }}
          password: ${{ secrets.DOCKERACR_TOKEN }}
          
      - run: |
          docker build -t acrcomunidadecloud.azurecr.io/mycontainer:$(date +%s) .
          docker push acrcomunidadecloud.azurecr.io/mycontainer:$(date +%s)
